config/routes.rb
Amazon::Application.routes.draw do
  resources :scripts
  root to: 'scripts#index'

end

app/models/script.rb
class Script < ActiveRecord::Base
  attr_accessible :base, :feedback_count, :model, :offers, :rating, :shipping, :source, :title, :top_seller, :total, :upc
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
 require 'open-uri'
  # GET /scripts
  # GET /scripts.json
  def index
    @scripts = Script.all

  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
    @script = Script.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @script }
    end
  end

  # GET /scripts/new
  # GET /scripts/new.json
  def new
    @script = Script.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @script }
    end
  end

  # GET /scripts/1/edit
  def edit
    @script = Script.find(params[:id])
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(params[:script])

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render json: @script, status: :created, location: @script }
      else
        format.html { render action: "new" }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scripts/1
  # PUT /scripts/1.json
  def update
    @script = Script.find(params[:id])

    respond_to do |format|
      if @script.update_attributes(params[:script])
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script = Script.find(params[:id])
    @script.destroy

    respond_to do |format|
      format.html { redirect_to scripts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazon</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <lays>
	<%= yield %>
  </lays>
</body>
</html>

app/views/scripts/_form.html.erb
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% @script.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= "What's the UPC Code?" %><br />
    <%= f.text_field :upc, id: "tall" %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>Edit the UPC</h1>

<%= render 'form' %>
<br><br><br><br>
<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/index.html.erb
<h1>Listing Upc's</h1>

<table>
  <tr>
    <th>Upc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scripts.each do |script| %>
  <tr>
    <td><h6><%= link_to script.upc, script %></h6></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><h3><%= link_to 'Edit', edit_script_path(script) %></h3></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><h3><%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' }, id: "red" %></h3></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New UPC', new_script_path, class: "btn btn-big btn-primary", id: "sign_btn2" %>

app/views/scripts/new.html.erb
<h1>New UPC</h1>

<%= render 'form' %><br><br><br><br>

<%= link_to 'Go Back', scripts_path %>

app/views/scripts/show.html.erb
<h1>UPC: <%= "#{@script.upc}" %></h1>
<p id="notice"><%= notice %></p>

<% amazon_url = "http://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=#{@script.upc}" %>
<% goog_url = "http://www.google.com/search?hl=en&tbm=shop&q=#{@script.upc}" %>
<% a_temp_doc = Nokogiri::HTML(open(amazon_url)) %>

<% if a_temp_doc.at('#result_0 a') %>
  <% a_real_url = a_temp_doc.at('#result_0 a')[:href] %>

  <% doc = Nokogiri::HTML(open(a_real_url)) %>
  <% doc.css("#handleBuy").each do |item| %>
    <% title = item.at_css("#btAsinTitle").content %>
    <% if item.at_css('.buyNewOffers .rentPrice') %>
      <% price = item.at_css(".buyNewOffers .rentPrice").text[/[0-9\.]+/] %>
    <% else %>
      <% price = item.at_css(".priceLarge").text[/[0-9\.]+/] %>
    <% end %>
    <% if item.at_css("#actualPriceExtraMessaging b") %>
      <% ship = item.at_css("#actualPriceExtraMessaging b").content %>
    <% else %>
      <% ship = item.at_css(".plusShippingText").content[/[0-9\.]+/] %>
    <% end %>
    <% if item.at_css('span.asinReviewsSummary a') %>
      <% stars = item.at_css('span.asinReviewsSummary a').text %>
    <% else %>
      <% stars = "No stars yet..." %>
    <% end %>
    <% reviews = item.xpath('//*[@id="handleBuy"]/div[2]/span[1]/span/a').text %>
    <% if item.at_css("#amsPopoverTrigger a") == nil  %>
      <% if item.at_css(".parseasinTitle+ span a") == nil %>
        <% top = "Amazon" %>
      <% else %>
        <% top = item.at_css(".parseasinTitle+ span a").text %>
      <% end %>
    <% else %>
      <% top = item.at_css("#amsPopoverTrigger a").text %>
    <% end %>

    <% if ship == "FREE Shipping" %>
      <% total = price %>
    <% else %>
      <% total = price.to_i + ship.to_i %>
    <% end %>
    <%= "From site: Amazon" %><br>
    <%= "Model: #{title} - Item Price: $#{price}" %><br>
    <% if ship == "FREE Shipping" %>
      <%= "#{ship}, & total price: $#{total}" %><br>
    <% else %>
      <%= "shipping: $#{ship}, total price: $#{total}" %><br>
    <% end %>
    <%= "Top Seller: #{top}" %><br>
    <%= "#{stars}" %><br>
    <%= "#{reviews}" %><br>

    <% File.open("amazon.csv", "ab") do |csv| %>
      <% csv << ["Site", "Amazon"] %>
      <% csv << ["Item Price", "#{price}"] %>
      <% csv << ["Shipping", "#{ship}"] %>
      <% csv << ["Total Price", "#{total}"] %>
      <% csv << ["Top Seller", "#{top}"] %>
      <% csv << ["UPC #", "#{@script.upc}"]  %>
      <% csv << ["#{stars}"] %>
      <% csv << ["#{reviews}"] %>
    <% end %>
  <% end %>
<% else %>
  <%= "No results from Amazon Marketplace.." %><br><br>
<% end %>

<br>

<% g_doc = Nokogiri::HTML(open(goog_url)) %>
<% if (g_doc.at('p:nth-child(1)').nil?) %>
  <% g_doc.css("#ires").each do |item| %>
    <% title = item.at_css("#ires , .pslimain a").content %>
    <% price = item.css(".psliprice b").first.content[/[0-9\.]+/] %>
    <% top = item.css('cite').first.text %>
    <% reviews = item.css('cite[4] a').text %>
    <%= "From site: Google" %><br>
    <%= "Model: #{title} - Item Price: #{price}" %><br>
    <%= "Top Seller: #{top}" %><br>
    <%= "#{reviews}" %><br>

    <% File.open("google.csv", "ab") do |csv| %>
      <% csv << ["Site", "Google"] %>
      <% csv << ["Item Price", "#{price}"] %>
      <% csv << ["Top Seller", "#{top}"] %>
      <% csv << ["UPC #", "#{@upc}"] %>
      <% csv << ["#{Time.now.strftime('%m/%d/%Y %H:%M')}"] %>
    <% end %>
  <% end %>
<% else %>
  <%= "No results from Google Shopping..." %><br>
<% end %>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>